# These are supported funding model platforms

github: sunstep
patreon: thesunstep
open_collective: thesunstep
ko_fi: sunstep
liberapay: sunstep
buy_me_a_coffee: sunstep
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

