// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    pointGeometryTable,
    pointPropertiesTable,
    pointsTable,
    statsCache,
    trackTable,
    trackerSettingsTable,
    userTable,
    userSettingsTable,
  ];
  late final Shape0 pointGeometryTable = Shape0(
      source: i0.VersionedTable(
        entityName: 'point_geometry_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 pointPropertiesTable = Shape1(
      source: i0.VersionedTable(
        entityName: 'point_properties_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 pointsTable = Shape2(
      source: i0.VersionedTable(
        entityName: 'points_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(deduplication_key)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape3 statsCache = Shape3(
      source: i0.VersionedTable(
        entityName: 'stats_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(id)',
        ],
        columns: [
          _column_23,
          _column_24,
          _column_25,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 trackTable = Shape4(
      source: i0.VersionedTable(
        entityName: 'track_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 trackerSettingsTable = Shape5(
      source: i0.VersionedTable(
        entityName: 'tracker_settings_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(user_id)',
        ],
        columns: [
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 userTable = Shape6(
      source: i0.VersionedTable(
        entityName: 'user_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(dawarich_id, dawarich_endpoint)',
        ],
        columns: [
          _column_0,
          _column_36,
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 userSettingsTable = Shape7(
      source: i0.VersionedTable(
        entityName: 'user_settings_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_54,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_59,
          _column_60,
          _column_61,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get longitude =>
      columnsByName['longitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get latitude =>
      columnsByName['latitude']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        hasAutoIncrement: true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT');
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>('type', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_2(String aliasedName) =>
    i1.GeneratedColumn<double>('longitude', aliasedName, false,
        type: i1.DriftSqlType.double,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const i1.CustomExpression('0.0'));
i1.GeneratedColumn<double> _column_3(String aliasedName) =>
    i1.GeneratedColumn<double>('latitude', aliasedName, false,
        type: i1.DriftSqlType.double,
        $customConstraints: 'NOT NULL DEFAULT 0.0',
        defaultValue: const i1.CustomExpression('0.0'));

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get batteryState =>
      columnsByName['battery_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get batteryLevel =>
      columnsByName['battery_level']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get wifi =>
      columnsByName['wifi']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get recordTimestamp =>
      columnsByName['record_timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get providerTimestamp =>
      columnsByName['provider_timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get altitude =>
      columnsByName['altitude']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get speed =>
      columnsByName['speed']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get horizontalAccuracy =>
      columnsByName['horizontal_accuracy']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get verticalAccuracy =>
      columnsByName['vertical_accuracy']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get speedAccuracy =>
      columnsByName['speed_accuracy']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get course =>
      columnsByName['course']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get courseAccuracy =>
      columnsByName['course_accuracy']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>('battery_state', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_5(String aliasedName) =>
    i1.GeneratedColumn<double>('battery_level', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>('wifi', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>('record_timestamp', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>('provider_timestamp', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_9(String aliasedName) =>
    i1.GeneratedColumn<double>('altitude', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_10(String aliasedName) =>
    i1.GeneratedColumn<double>('speed', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>('horizontal_accuracy', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_12(String aliasedName) =>
    i1.GeneratedColumn<double>('vertical_accuracy', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_13(String aliasedName) =>
    i1.GeneratedColumn<double>('speed_accuracy', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>('course', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<double> _column_15(String aliasedName) =>
    i1.GeneratedColumn<double>('course_accuracy', aliasedName, false,
        type: i1.DriftSqlType.double, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>('track_id', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>('device_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get geometryId =>
      columnsByName['geometry_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get propertiesId =>
      columnsByName['properties_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deduplicationKey =>
      columnsByName['deduplication_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isUploaded =>
      columnsByName['is_uploaded']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>('geometry_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES point_geometry_table(id)');
i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>('properties_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES point_properties_table(id)');
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>('deduplication_key', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>('user_id', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>('is_uploaded', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_uploaded IN (0, 1))',
        defaultValue: const i1.CustomExpression('0'));

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payloadJson =>
      columnsByName['payload_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>('id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1',
        defaultValue: const i1.CustomExpression('1'));
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>('synced_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>('payload_json', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get trackId =>
      columnsByName['track_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startTimestamp =>
      columnsByName['start_timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endTimestamp =>
      columnsByName['end_timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get active =>
      columnsByName['active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>('track_id', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>('start_timestamp', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>('end_timestamp', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>('active', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL DEFAULT 1 CHECK (active IN (0, 1))',
        defaultValue: const i1.CustomExpression('1'));

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get automaticTracking =>
      columnsByName['automatic_tracking']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get trackingFrequency =>
      columnsByName['tracking_frequency']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get locationAccuracy =>
      columnsByName['location_accuracy']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get minimumPointDistance =>
      columnsByName['minimum_point_distance']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get pointsPerBatch =>
      columnsByName['points_per_batch']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>('automatic_tracking', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NULL CHECK (automatic_tracking IN (0, 1))');
i1.GeneratedColumn<int> _column_31(String aliasedName) =>
    i1.GeneratedColumn<int>('tracking_frequency', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>('location_accuracy', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>('minimum_point_distance', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>('points_per_batch', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>('device_id', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dawarichId =>
      columnsByName['dawarich_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get dawarichEndpoint =>
      columnsByName['dawarich_endpoint']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get email =>
      columnsByName['email']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get theme =>
      columnsByName['theme']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get admin =>
      columnsByName['admin']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_36(String aliasedName) =>
    i1.GeneratedColumn<int>('dawarich_id', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>('dawarich_endpoint', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>('email', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>('created_at', aliasedName, false,
        type: i1.DriftSqlType.int, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_40(String aliasedName) =>
    i1.GeneratedColumn<int>('updated_at', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_41(String aliasedName) =>
    i1.GeneratedColumn<String>('theme', aliasedName, false,
        type: i1.DriftSqlType.string, $customConstraints: 'NOT NULL');
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>('admin', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL CHECK (admin IN (0, 1))');

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get immichUrl =>
      columnsByName['immich_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get immichApiKey =>
      columnsByName['immich_api_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoprismUrl =>
      columnsByName['photoprism_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get photoprismApiKey =>
      columnsByName['photoprism_api_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get distanceUnit =>
      columnsByName['distance_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fogOfWarMeters =>
      columnsByName['fog_of_war_meters']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get metersBetweenRoutes =>
      columnsByName['meters_between_routes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get preferredMapLayer =>
      columnsByName['preferred_map_layer']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get speedColoredRoutes =>
      columnsByName['speed_colored_routes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get pointsRenderingMode =>
      columnsByName['points_rendering_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get minutesBetweenRoutes =>
      columnsByName['minutes_between_routes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timeThresholdMinutes =>
      columnsByName['time_threshold_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mergeThresholdMinutes =>
      columnsByName['merge_threshold_minutes']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get liveMapEnabled =>
      columnsByName['live_map_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get routeOpacity =>
      columnsByName['route_opacity']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get visitsSuggestionsEnabled =>
      columnsByName['visits_suggestions_enabled']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get speedColorScale =>
      columnsByName['speed_color_scale']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fogOfWarThreshold =>
      columnsByName['fog_of_war_threshold']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>('user_id', aliasedName, false,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NOT NULL REFERENCES user_table(id)');
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>('immich_url', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>('immich_api_key', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>('photoprism_url', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>('photoprism_api_key', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>('distance_unit', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>('fog_of_war_meters', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>('meters_between_routes', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>('preferred_map_layer', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>('speed_colored_routes', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NULL CHECK (speed_colored_routes IN (0, 1))');
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>('points_rendering_mode', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>('minutes_between_routes', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>('time_threshold_minutes', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_56(String aliasedName) =>
    i1.GeneratedColumn<int>('merge_threshold_minutes', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_57(String aliasedName) =>
    i1.GeneratedColumn<int>('live_map_enabled', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints: 'NULL CHECK (live_map_enabled IN (0, 1))');
i1.GeneratedColumn<double> _column_58(String aliasedName) =>
    i1.GeneratedColumn<double>('route_opacity', aliasedName, true,
        type: i1.DriftSqlType.double, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>('visits_suggestions_enabled', aliasedName, true,
        type: i1.DriftSqlType.int,
        $customConstraints:
            'NULL CHECK (visits_suggestions_enabled IN (0, 1))');
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>('speed_color_scale', aliasedName, true,
        type: i1.DriftSqlType.string, $customConstraints: 'NULL');
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>('fog_of_war_threshold', aliasedName, true,
        type: i1.DriftSqlType.int, $customConstraints: 'NULL');

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    pointGeometryTable,
    pointPropertiesTable,
    pointsTable,
    userTable,
    statsCache,
    trackTable,
    trackerSettingsTable,
    userSettingsTable,
  ];
  late final Shape0 pointGeometryTable = Shape0(
      source: i0.VersionedTable(
        entityName: 'point_geometry_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_1,
          _column_2,
          _column_3,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape1 pointPropertiesTable = Shape1(
      source: i0.VersionedTable(
        entityName: 'point_properties_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_4,
          _column_5,
          _column_6,
          _column_7,
          _column_8,
          _column_9,
          _column_10,
          _column_11,
          _column_12,
          _column_13,
          _column_14,
          _column_15,
          _column_16,
          _column_17,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape2 pointsTable = Shape2(
      source: i0.VersionedTable(
        entityName: 'points_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(deduplication_key)',
        ],
        columns: [
          _column_0,
          _column_1,
          _column_18,
          _column_19,
          _column_20,
          _column_21,
          _column_22,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape6 userTable = Shape6(
      source: i0.VersionedTable(
        entityName: 'user_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'UNIQUE(dawarich_id, dawarich_endpoint)',
        ],
        columns: [
          _column_0,
          _column_36,
          _column_37,
          _column_38,
          _column_39,
          _column_40,
          _column_41,
          _column_42,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape8 statsCache = Shape8(
      source: i0.VersionedTable(
        entityName: 'stats_cache',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(user_id)',
        ],
        columns: [
          _column_43,
          _column_24,
          _column_25,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape4 trackTable = Shape4(
      source: i0.VersionedTable(
        entityName: 'track_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_26,
          _column_27,
          _column_28,
          _column_29,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape5 trackerSettingsTable = Shape5(
      source: i0.VersionedTable(
        entityName: 'tracker_settings_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [
          'PRIMARY KEY(user_id)',
        ],
        columns: [
          _column_30,
          _column_31,
          _column_32,
          _column_33,
          _column_34,
          _column_35,
          _column_21,
        ],
        attachedDatabase: database,
      ),
      alias: null);
  late final Shape7 userSettingsTable = Shape7(
      source: i0.VersionedTable(
        entityName: 'user_settings_table',
        withoutRowId: false,
        isStrict: false,
        tableConstraints: [],
        columns: [
          _column_0,
          _column_43,
          _column_44,
          _column_45,
          _column_46,
          _column_47,
          _column_48,
          _column_49,
          _column_50,
          _column_51,
          _column_52,
          _column_53,
          _column_54,
          _column_55,
          _column_56,
          _column_57,
          _column_58,
          _column_59,
          _column_60,
          _column_61,
        ],
        attachedDatabase: database,
      ),
      alias: null);
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get userId =>
      columnsByName['user_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get syncedAt =>
      columnsByName['synced_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get payloadJson =>
      columnsByName['payload_json']! as i1.GeneratedColumn<String>;
}

i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) =>
    i0.VersionedSchema.stepByStepHelper(
        step: migrationSteps(
      from5To6: from5To6,
      from6To7: from6To7,
    ));
